
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 22 19:59:35 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LPARENT = 6;
  public static final int RPARENT = 7;
  public static final int LBRACKET = 8;
  public static final int CHAR = 44;
  public static final int CONST = 18;
  public static final int NAMESPACE = 17;
  public static final int NOT_EQUAL = 23;
  public static final int GREATER = 24;
  public static final int SEMI = 5;
  public static final int CONTINUE = 29;
  public static final int LESS = 26;
  public static final int MINUS = 34;
  public static final int STATIC = 19;
  public static final int AND = 33;
  public static final int OR = 32;
  public static final int BOOL = 43;
  public static final int COMMA = 10;
  public static final int DDOT = 20;
  public static final int INC = 30;
  public static final int DIV = 37;
  public static final int LESS_EQUAL = 27;
  public static final int PLUS = 13;
  public static final int IF = 39;
  public static final int ASSIGN = 22;
  public static final int DOT = 21;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int RBRACKET = 9;
  public static final int EQUAL = 14;
  public static final int GREATER_EQUAL = 25;
  public static final int NEW = 35;
  public static final int error = 1;
  public static final int MUL = 36;
  public static final int NUMBER = 42;
  public static final int MOD = 38;
  public static final int IDENT = 41;
  public static final int BREAK = 28;
  public static final int VOID = 15;
  public static final int ELSE = 40;
  public static final int LBRACE = 3;
  public static final int READ = 16;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int DEC = 31;
  public static final int PRINT = 11;
}

